apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openempi-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openempi
  labels:
    app: openempi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openempi
  template:
    metadata:
      labels:
        app: openempi
    spec:
      containers:
        - name: openempi
          image: openempi-app:latest
          imagePullPolicy: Never          # usa imagen local de Minikube
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: openempi-logs
              mountPath: /opt/openempi/logs
          readinessProbe:
            httpGet:
              path: /openempi-admin
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 10
      volumes:
        - name: openempi-logs
          persistentVolumeClaim:
            claimName: openempi-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openempi
spec:
  selector:
    app: openempi
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort          # accesible desde el host via minikube service
